### PR TITLE
Add model for iCubGenova02 plus.

### PR DESCRIPTION
**Pull request by fiorisi**
As suggested by @fjandrad, we might need to have also the `plus` version for the robot `iCubGenova02`.

### CODE REVIEW

**Comment by traversaro** [comment]
It is a bit silly, but I think we should track as much as possible the real robots for the `iCubGenovaXX` models. If we modify the ankle, I think we should modify the model, if we modify back the robot, we should modify the model again. For now I would modify the `iCubGenova02` as soon as the new ankle is installed, as it is the only way to make sure that the `wholebodydynamics` picks the right model for estimation.

**Comment by traversaro** [comment]
This is clearly a case in which the automatic generation is essential.

**Comment by fiorisi** [comment]
The model `iCubGenova02_plus` has been deleted and the model `iCubGenova02` has been updated with the "plus" modifications (15 [deg] on ankle pitch offset and root link IMU). Nevertheless, the real robot `iCubGenova02` currently has not the root link IMU.

**Comment by traversaro** [comment]
A good old case of combinatorial model explosion. : )

As long as no one uses it, the IMU frame is not going to affect the model, right? 
Unfortunately I think this will introduce a small error in the inertial parameters of the root link due to the missing IMU, right?

**Comment by fiorisi** [comment]
Yes, the IMU is 55 [g] (see page 63 of the [manual](http://www.farnell.com/datasheets/1935846.pdf)). Probably is negligible.

**Comment by traversaro** [comment]
> Yes, the IMU is 55 [g] (see page 63 of the manual). Probably is negligible?

Between the 15 degrees offset and a 55 g offset, I guess the lesser evil is definitly the 55 g offset. : )

**Comment by traversaro** [comment]
Ok, I guess some consistency checks need to be modified.

**Pull request merged**
