### PR TITLE
icub3: add first draft

### PR DESCRIPTION
**Pull request by Nicogene**
~This PR adds the icub3 upperbody files in order to generate the urdf correctly~

This PR add the whole model and sub-models except for the forarms.

The model has been generated from this hash commit `28cb95f2859090d7be896662079e77d3cc4a27df` of cad-mechanics

### CODE REVIEW

**Comment by Nicogene** [comment]
I managed to generate the urdf from cmake, shall we merge this intermediate result? Or do we wait to have something more complete?

**Comment by traversaro** [comment]
Anything that is merged in master gets immediately deployed on `icub-models/master`. For this reason. probably we can just merge in an integration branch, and you can attach manually the URDF model to the issue for people to test. Once we have a minimally working model, we can push it on `master`.

**Comment by Nicogene** [comment]
I agree we can keep it where it is and then merge when we have something more complete

**Comment by traversaro** [comment]
Can you remove the file `simmechanics/data/icub3/ConversionProcess.xlsx` ? It is quite heavy and not related at all to iCub 3.

**Comment by traversaro** [comment]
Can you add some details on which version of cad-mechanics genarate teh used simmechanics xml files?

**Review by traversaro — APPROVED** [review]

**Pull request merged**
