### PR TITLE
 Cleanup reference to robotology-playground 

### PR DESCRIPTION
**Pull request by traversaro**
Cleanup necessary after https://github.com/robotology/icub-model-generator/issues/66 and https://github.com/robotology/icub-models/issues/14 .

### CODE REVIEW

**Comment by fiorisi** [comment]
@traversaro considering the [build error](https://travis-ci.org/robotology/icub-model-generator/builds/393597311#L4923), do you think that the solution is to update the version in [this CMake file](https://github.com/robotology/icub-main/blob/master/CMakeLists.txt#L25)?

**Comment by traversaro** [comment]
The build error is due to the current incompatibility between YARP master and ICUB master, see https://github.com/robotology/QA/issues/300 . Given https://github.com/robotology/icub-model-generator/issues/94 , I think I will do a pass over the travis script to clean it up.

**Comment by traversaro** [comment]
Should be fixed by https://github.com/robotology/icub-model-generator/pull/93/commits/6f2898447aed01f55d0075d7b193ac5fe93d2cf0 .

**Comment by traversaro** [comment]
Travis is finally green. @fiorisi feel free to "Squash and merge" to remove all the trial commits.

**Comment by traversaro** [comment]
@fiorisi Apparently you clicked on "merge", for the future please click on ["Squash and merge"](https://help.github.com/articles/about-pull-request-merges/#squash-and-merge-your-pull-request-commits) to avoid committing a lot of dirty commits in the history of the repo, thanks!

**Pull request merged**
