### PR TITLE
[Travis] Switch to Ubuntu 18.04 Bionic and add workaround for urdf_parser_py regression

### PR DESCRIPTION
**Pull request by traversaro**
See  https://github.com/robotology/simmechanics-to-urdf/issues/36 and https://github.com/ros/urdf_parser_py/pull/47 for more info on the regression. 
See https://docs.travis-ci.com/user/reference/bionic/ for the Ubuntu 18.04 Bionic. 

If this is successful, hopefully it would simplify reproducing the Travis failure in https://travis-ci.org/robotology/icub-model-generator/builds/570949195 mentioned in https://github.com/robotology/icub-model-generator/pull/113#issuecomment-522576137  .

### CODE REVIEW

**Comment by prashanthr05** [comment]
Any update on this?

**Comment by traversaro** [comment]
Let's see. 

The latest error is: 
~~~
/usr/bin/ld: cannot find -lconsole_bridge::console_bridge

collect2: error: ld returned 1 exit status
~~~

This should have been fixed by https://github.com/robotology/icub-model-generator/pull/116/commits/f2a4ce27f171543e7f8b4d2d6c8e2b77eec66da0, but it did not. Let's see why.

**Comment by traversaro** [comment]
To move the CI system closer to my system (where everything was working fine), in https://github.com/robotology/icub-model-generator/pull/116/commits/1fafc9d6e86524a6a02ee82f595e477134ca8cd5 I switched to use the Ubuntu packages for `orocos_kdl`, `console_bridge`, `urdfdom_headers` and `urdfdom`.

**Comment by traversaro** [comment]
The latest failure is much more interesting, for dh-generated  models we have this problem: 
> icub-model-test error:torso_pitch got direction of  x 0 y 1 z 6.12323e-17 instead of expected  x 0 y -1 z 0 

Probably something changed in some of the dependency related to dh-models generation: iDynTree, YARP or icub-main .

**Comment by traversaro** [comment]
Superseded by https://github.com/robotology/icub-model-generator/pull/119 .

**Pull request closed without merging**
